org.gradle.jvmargs=-Xmx3G

#Mod Settings
groupId=com.craftjakob
mod_id=gildednetherite
mod_name=Gilded Netherite CJ Edition
mod_version=1.1.2
mod_authors=Craftjakob
archives_base_name=GildedNetherite-CJ
enabled_platforms=fabric,forge,quilt

#Publishing Settings
curseforge_id=646970
modrinth_id=gildednetherite-cj-edition
mc_versions=1.20,1.20.1,1.20.2,1.20.4

#Dependencies
minecraft_version=1.20
architectury_version=9.1.13
forge_version=1.20-46.0.14
fabric_loader_version=0.15.6
fabric_api_version=0.83.0+1.20
quilt_loader_version=0.23.1
quilt_fabric_api_version=7.0.1+0.83.0-1.20
configapi_version=1.20-1.2.0

#More Settings (META-INF, pack.mcmeta, fabric.mod.json, quilt.mod.json, *.mixins.json)
mod_license=MIT License
minecraft_version_range=[1.20,1.21)
forge_version_range=[46,)
forge_loader_version_range=[46,)
mod_credits=Thank you for installing the Mod!
mod_issueTrackerURL=https://github.com/Craftjakob/Gilded-Netherite-CJ/issues
mod_updateJSONURL=https://www.curseforge.com/minecraft/mc-mods/gildednetherite-cj-edition/files
mod_displayURL=https://www.curseforge.com/minecraft/mc-mods/gildednetherite-cj-edition/
mod_description=Gilded Netherite makes piglins peaceful.\
You can craft better Armor, Tools and more.